### ISSUE TITLE
__scanCodes is not defined 

### ISSUE THREAD

**Issue by chaudev** [rodgomesc/vision-camera-code-scanner#107]
Help me, please !!!

- This is my "babel.config.js"

`plugins: [
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__scanQRCodes'],
      },
    ],
  ],`

- i tried:
`project.ext.react = [
    enableHermes: false
]`
----
`project.ext.react = [
    enableHermes: true
]`
----
`yarn start --reset-cache`

-  All are not working.

----

- react-native: 0.70.1
- vision-camera-code-scanner: 0.2.0
- Mac M1
- Android Device

**Comment by irodeanu** [comment]
I resolved with that: https://github.com/rodgomesc/vision-camera-code-scanner/issues/79#issuecomment-1276041982

**Comment by hosijyun** [comment]
Try adding one line to the file 'VisionCameraCodeScanner.m' as shown below.

@interface VISION_EXPORT_SWIFT_FRAME_PROCESSOR(scanCodes, VisionCameraCodeScanner)
-(void)stub {}
@end

**Comment by Moatezz** [comment]
> Try adding one line to the file 'VisionCameraCodeScanner.m' as shown below.
> 
> @interface VISION_EXPORT_SWIFT_FRAME_PROCESSOR(scanCodes, VisionCameraCodeScanner) -(void)stub {} @EnD

Where is the 
path of this file?

**Comment by valery-lavrik** [comment]
One of the branches says that the fix was made in version 2.15.2, but I still have this error in android.

**Comment by Peege151** [comment]
I still have this error running from the example.

**Comment by kaivamannam** [comment]
plugins: [[
    'react-native-reanimated/plugin',
  {
    globals: ['__scanCodes'], // https://github.com/rodgomesc/vision-camera-code-scanner
  }
  ]]

I have '__scanCodes' instead of '__scanQRCodes' and it works for me

**Comment by nhatnguyen95** [comment]
the issue happens on Android with typescript enabled.
- "react-native": "0.69.4"
- "react-native-vision-camera": "2.15.2"
- "vision-camera-code-scanner": "^0.2.0

**Comment by Bijiabo** [comment]
This problem has bothered me for a long time, after update `react-native-vision-camera` to `2.15.2`, this error disappear.
